---
# tasks file for ros_get
- name: get config"
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    ssl: "{{ ros_ssl }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_path }}"
  register: print_path
  delegate_to: localhost

- name: result config"
  debug:
    msg: '{{ print_path }}'
