---
- name: flush interface bridge {{ ros_int_brige_addfilter_type }}
  import_role:
    name: nikolaydachev.routeros_api.ros_flush
  vars:
    ros_flush_path: "{{ ros_int_brige_addfilter_path }}"
  when: ros_ip_firewall_flush == "true"

- name: add interface bridge {{ ros_int_brige_addfilter_type }}
  import_role:
    name: nikolaydachev.routeros_api.ros_add
  vars:
    ros_add_path: "{{ ros_int_brige_addfilter_path }}"
    ros_add_list: "{{ ros_int_brige_addfilter_rules }}"