---
- name: add routing ospf sham-link
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    ssl: "{{ ros_ssl }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_routing_ospf_sham_link_path }}"
    add:
      comment="{{ ros_routing_ospf_sham_link_comment }}"
      copy-from="{{ ros_routing_ospf_sham_link_copy_from }}"
      cost="{{ ros_routing_ospf_sham_link_cost }}"
      disabled="{{ ros_routing_ospf_sham_link_disabled }}"
      area="{{ ros_routing_ospf_sham_link_area }}"
      dst-address="{{ ros_routing_ospf_sham_link_dst_address }}"
      src-address="{{ ros_routing_ospf_sham_link_src_address }}"
  register: routingospfshamlinkout
  delegate_to: localhost
  