---
- name: configure certificate issued-revoke
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    ssl: "{{ ros_ssl }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_certificates_path }}"
    cmd:
      issued-revoke
      numbers={{ ros_certificates_issued_revoke }}

  register: certificateissuedrevoke
  delegate_to: localhost

- name: result configure certificate issued-revoke
  debug:
    msg: "{{ certificateissuedrevoke }}"
