---
# tasks file for ros_certificates
  - import_tasks: add.yml 
    when: '"add" in ros_certificates_config'
  - import_tasks: sign.yml 
    when: '"sign" in ros_certificates_config'
  - import_tasks: create-certificate-request.yml 
    when: '"create-certificate-request" in ros_certificates_config'
  - import_tasks: sign-certificate-request.yml 
    when: '"sign-certificate-request" in ros_certificates_config'
  - import_tasks: crl.yml 
    when: '"crl" in ros_certificates_config'
  - import_tasks: export-certificate.yml 
    when: '"export-certificate" in ros_certificates_config'
  - import_tasks: import.yml 
    when: '"import" in ros_certificates_config'
  - import_tasks: issued-revoke.yml 
    when: '"issued-revoke" in ros_certificates_config'
  - import_tasks: settings.yml 
    when: '"settings" in ros_certificates_config'
