---
# tasks file for ros_certificates
  - import_tasks: add.yml #1
    when: '"add" in ros_certificates_config'
  - import_tasks: sign.yml #1
    when: '"sign" in ros_certificates_config'
  - import_tasks: create-certificate-request.yml #1
    when: '"create-certificate-request" in ros_certificates_config'
  - import_tasks: sign-certificate-request.yml #1
    when: '"sign-certificate-request" in ros_certificates_config'
  - import_tasks: crl.yml #1
    when: '"crl" in ros_certificates_config'
  - import_tasks: export-certificate.yml #1
    when: '"export-certificate" in ros_certificates_config'
  - import_tasks: import.yml #1
    when: '"import" in ros_certificates_config'
  - import_tasks: issued-revoke.yml #1
    when: '"issued-revoke" in ros_certificates_config'
  - import_tasks: settings.yml #1
    when: '"settings" in ros_certificates_config'
