---
- name: configure certificate sign-certificate-request
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    ssl: "{{ ros_ssl }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_certificates_path }}"
    cmd:
      sign-certificate-request
      days-valid="{{ ros_certificates_sign_certificate_request_days_valid }}"
      ca="{{ ros_certificates_sign_certificate_request_ca }}"
      file-name="{{ ros_certificates_sign_certificate_request_file_name }}"

  register: certificatesigncertificaterequest
  delegate_to: localhost

- name: result configure certificate sign-certificate-request
  debug:
    msg: "{{ certificatesigncertificaterequest }}"
