---
- name: flush ip firewall
  import_role:
    name: nikolaydachev.routeros_api.ros_flush
  vars:
    ros_flush_path: "{{ ros_ip_fw_path }}"
  when: ros_ip_firewall_flush == "true"

- name: add ip firewall
  import_role:
    name: nikolaydachev.routeros_api.ros_add
  vars:
    ros_add_path: "{{ ros_ip_fw_path }}"
    ros_add_list: "{{ ros_ip_fw_rules }}"