---
- name: query ip firewall {{ ros_ip_fw_type }}
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    ssl: "{{ ros_ssl }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_ip_fw_path }}"
    query: ".id"
  register: rosipfirewallflushfind
  delegate_to: localhost

- name: set fact for ".id" from "query ip firewall {{ ros_ip_fw_type }}"
  ansible.builtin.set_fact:
    to_be_remove: "{{ to_be_remove |default([]) + [item['msg'][0]['.id']] }}"
  loop: "{{ rosipfirewallflushfind.results }}"

- name: flush subtask ip firewall {{ ros_ip_fw_type }}
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    ssl: "{{ ros_ssl }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_ip_fw_path }}"
    remove: "{{ item }}"
  register: rosipfirewallflush
  delegate_to: localhost
  loop: "{{ to_be_remove }}"



