---
- name: query ip firewall {{ ros_ip_fw_type }}
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    ssl: "{{ ros_ssl }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_ip_fw_path }}"
    query: ".id"
  register: rosipfirewallflushfind
  delegate_to: localhost

- name: create a list of query result for {{ ros_ip_fw_type }}
  vars:
    to_be_remove: ""
  ansible.builtin.set_fact:
    to_be_remove: "{{ to_be_remove + ',' + item['.id'] }}"
  loop: "{{ rosipfirewallflushfind.msg }}"
  when: '"no results for" not in rosipfirewallflushfind.msg.0'

- name: flush ip firewall {{ ros_ip_fw_type }}
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    ssl: "{{ ros_ssl }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_ip_fw_path }}"
    remove: "{{ to_be_remove }}"
  register: rosipfirewallflush
  delegate_to: localhost
  when: to_be_remove is defined
