---
# tasks file for ros_ip_firewall
  - name: "ip firewall address-list"
    import_tasks: add.yml
    vars:
      ros_ip_fw_type: "address-list"
      ros_ip_fw_path: "{{ ros_ip_firewall_address_list_path }}"
      ros_ip_fw_rules: "{{ ros_ip_firewall_address_list }}"
    when: '"address-list" in ros_ip_firewall_config'

  - name: "ip firewall calea"
    import_tasks: add.yml
    vars:
      ros_ip_fw_type: "calea"
      ros_ip_fw_path: "{{ ros_ip_firewall_calea_path }}"
      ros_ip_fw_rules: "{{ ros_ip_firewall_calea }}"
    when: '"calea" in ros_ip_firewall_config'

  - name: "ip firewall calea"
    import_tasks: add.yml
    vars:
      ros_ip_fw_type: "filter"
      ros_ip_fw_path: "{{ ros_ip_firewall_filter_path }}"
      ros_ip_fw_rules: "{{ ros_ip_firewall_filter }}"
    when: '"filter" in ros_ip_firewall_config'

  - name: "ip firewall layer7-protocol"
    import_tasks: add.yml
    vars:
      ros_ip_fw_type: "layer7-protoco"
      ros_ip_fw_path: "{{ ros_ip_firewall_layer7_protocol_path }}"
      ros_ip_fw_rules: "{{ ros_ip_firewall_layer7_protocol }}"
    when: '"layer7-protocol" in ros_ip_firewall_config'

  - name: "ip firewall mangle"
    import_tasks: add.yml
    vars:
      ros_ip_fw_type: "mangle"
      ros_ip_fw_path: "{{ ros_ip_firewall_mangle_path }}"
      ros_ip_fw_rules: "{{ ros_ip_firewall_mangle }}"
    when: '"mangle" in ros_ip_firewall_config'

  - name: "ip firewall nat"
    import_tasks: add.yml
    vars:
      ros_ip_fw_type: "nat"
      ros_ip_fw_path: "{{ ros_ip_firewall_nat_path }}"
      ros_ip_fw_rules: "{{ ros_ip_firewall_nat }}"
    when: '"nat" in ros_ip_firewall_config'
    
  - name: "ip firewall raw"
    import_tasks: add.yml
    vars:
      ros_ip_fw_type: "raw"
      ros_ip_fw_path: "{{ ros_ip_firewall_raw_path }}"
      ros_ip_fw_rules: "{{ ros_ip_firewall_raw }}"
    when: '"raw" in ros_ip_firewall_config'

  - import_tasks: connection_tracking.yml
    when: '"connection-tracking" in ros_ip_firewall_config'

  - import_tasks: service_port.yml
    when: '"service-port" in ros_ip_firewall_config'
