---
- name: configure ipsec
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    ssl: "{{ ros_ssl }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_ip_ipsec__path }}"
    add:

  register: ipsec
  delegate_to: localhost

- name: result configure ipsec
  debug:
    msg: "{{ ipsec }}"

