---
- name: configure ipsec settings
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    ssl: "{{ ros_ssl }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_ip_ipsec_settings_path }}"
    cmd:
      set
      accounting="{{ ros_ip_ipsec_settings_accounting }}"
      interim-update="{{ ros_ip_ipsec_settings_interim_update }}"
      xauth-use-radius="{{ ros_ip_ipsec_settings_xauth_use_radius }}"
  register: ipsecsettings
  delegate_to: localhost

- name: result configure ipsec settings
  debug:
    msg: "{{ ipsecsettings }}"

