---
- name: configure ipsec installed-sa
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    ssl: "{{ ros_ssl }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_ip_ipsec_installed_sa_path }}"
    cmd:
      flush
  register: ipsecinstalledsa
  delegate_to: localhost

- name: result configure ipsec installed-sa
  debug:
    msg: "{{ ipsecinstalledsa }}"

