---
- name: configure tool romon port
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    ssl: "{{ ros_ssl }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_tool_romon_port_path }}"
    add:
      comment={{ ros_tool_romon_port_comment }}
      copy-from={{ ros_tool_romon_port_copy_from }}
      cost ={{ ros_tool_romon_port_cost }}"
      disabled={{ ros_tool_romon_port_disabled }}
      forbid={{ ros_tool_romon_port_forbid }
      secrets={{ ros_tool_romon_port_secrets }}
      interface={{ ros_tool_romon_port_interface }}
  register: toolromonport
  delegate_to: localhost

- name: result configure tool romon port
  debug:
    msg: "{{ toolromonport }}"
