---
- name: configure dhcp server network
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    ssl: "{{ ros_ssl }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_ip_dhcp_server_network_path }}"
    add:
      address="{{ ros_ip_dhcp_server_network_address }}"
      boot-file-name="{{ ros_ip_dhcp_server_network_boot_file_name }}"
      caps-manager="{{ ros_ip_dhcp_server_network_caps_manager }}"
      comment="{{ ros_ip_dhcp_server_network_comment }}"
      dhcp-option="{{ ros_ip_dhcp_server_network_dhcp_option }}"
      dhcp-option-set="{{ ros_ip_dhcp_server_network_dhcp_option_set }}"
      dns-none="{{ ros_ip_dhcp_server_network_dns_none }}"
      dns-server="{{ ros_ip_dhcp_server_network_dns_server }}"
      domain="{{ ros_ip_dhcp_server_network_domain }}"
      gateway="{{ ros_ip_dhcp_server_network_gateway }}"
      netmask="{{ ros_ip_dhcp_server_network_netmask }}"
      ntp-server="{{ ros_ip_dhcp_server_network_ntp_server }}"
      wins-server="{{ ros_ip_dhcp_server_network_wins_server }}"
      next-server="{{ ros_ip_dhcp_server_network_next_server }}"

  register: dhcpnetout
  delegate_to: localhost

- name: result configure dhcp server network
  debug:
    msg: "{{ dhcpnetout }}"

