---
- name: configure dhcp server
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    ssl: "{{ ros_ssl }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_ip_dhcp_server_server_path }}"
    add:
      add-arp={{ ros_ip_dhcp_server_server_add_arp }}
      allow-dual-stack-queue={{ ros_ip_dhcp_server_server_allow_dual_stack_queue }}
      authoritative={{ ros_ip_dhcp_server_server_authoritative }}
      bootp-support={{ ros_ip_dhcp_server_server_bootp_support }}
      conflict-detection={{ ros_ip_dhcp_server_server_conflict_detection }}
      delay-threshold={{ ros_ip_dhcp_server_server_delay_threshold }}
      disabled={{ ros_ip_dhcp_server_server_disabled }}
      lease-script={{ ros_ip_dhcp_server_server_lease_script }}
      name={{ ros_ip_dhcp_server_server_name }}
      relay={{ ros_ip_dhcp_server_server_relay }}
      use-framed-as-classless={{ ros_ip_dhcp_server_server_use_framed_as_classless }}
      interface={{ ros_ip_dhcp_server_server_interface }}
      address-pool={{ ros_ip_dhcp_server_server_address_pool }}
      always-broadcast={{ ros_ip_dhcp_server_server_always_broadcast }}
      bootp-lease-time={{ ros_ip_dhcp_server_server_bootp_lease_time }}
      client-mac-limit={{ ros_ip_dhcp_server_server_client_mac_limit }}
      copy-from={{ ros_ip_dhcp_server_server_copy_from }}
      dhcp-option-set={{ ros_ip_dhcp_server_server_dhcp_option_set }}
      insert-queue-before={{ ros_ip_dhcp_server_server_insert_queue_before }}
      lease-time={{ ros_ip_dhcp_server_server_lease_time }}
      parent-queue={{ ros_ip_dhcp_server_server_parent_queue }}
      src-address={{ ros_ip_dhcp_server_server_src_address }}
      use-radius={{ ros_ip_dhcp_server_server_use_radius }}

  register: dhcpserverout
  delegate_to: localhost

- name: result configure dhcp server
  debug:
    msg: "{{ dhcpserverout }}"
