---
- name: configure dhcp server vendor class id
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    ssl: "{{ ros_ssl }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_ip_dhcp_server_vci_path }}"
    add:
      disabled="{{ ros_ip_dhcp_server_vci_disabled }}"
      vid="{{ ros_ip_dhcp_server_vci_vid }}"
      address-pool="{{ ros_ip_dhcp_server_vci_address_pool }}"
      name="{{ ros_ip_dhcp_server_vci_name }}"
      server{{ ros_ip_dhcp_server_vci_server }}"

  register: dhcpvciout
  delegate_to: localhost

- name: result configure dhcp server vendor class id
  debug:
    msg: "{{ dhcpvciout }}"
