---
- name: configure dhcp server options
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    ssl: "{{ ros_ssl }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_ip_dhcp_server_options_path }}"
    add:
      value={{ ros_ip_dhcp_server_options_value }}
      code={{ ros_ip_dhcp_server_options_code }}
      name={{ ros_ip_dhcp_server_options_name }}

  register: dhcpoptout
  delegate_to: localhost

- name: result configure dhcp server options
  debug:
    msg: "{{ dhcpoptout }}"





