---
# tasks file for ros_ip_dhcp_server
  - import_tasks: add_network.yml
    when: '"network" in ros_ip_dhcp_server_config'
  - import_tasks: add_server.yml
    when: '"server" in ros_ip_dhcp_server_config'
  - import_tasks: add_lease.yml
    when: '"lease" in ros_ip_dhcp_server_config'
  - import_tasks: add_options.yml
    when: '"options" in ros_ip_dhcp_server_config'
  - import_tasks: add_vci.yml
    when: '"vci" in ros_ip_dhcp_server_config'
