---
# tasks file for ros_ip_dhcp_server
  - import_tasks: network.yml
    when: '"network" in ros_ip_dhcp_server_config'
  - import_tasks: server.yml
    when: '"server" in ros_ip_dhcp_server_config'
  - import_tasks: lease.yml
    when: '"lease" in ros_ip_dhcp_server_config'
  - import_tasks: options.yml
    when: '"options" in ros_ip_dhcp_server_config'
  - import_tasks: vci.yml
    when: '"vci" in ros_ip_dhcp_server_config'
