- name: ros7 routing ospf 
  hosts: all
  gather_facts: no
  connection: local

  roles:
  - role: nikolaydachev.routeros_api.ros7_routing_ospf
    ros7_routing_ospf_config:
      - instance
      - area
#      - area_range
      - interface-template
#      - static-neighbor


