- name: ros ip firewall
  hosts: all
  gather_facts: no
  connection: local

  roles:
  - role: nikolaydachev.routeros_api.ros_ip_firewall
    ros_ip_firewall_config:
      - address-list
#      - calea
      - filter
#      - layer7-protocol
#      - mangle
      - nat
#      - raw
#      - connection_tracking
#      - service-port
