- name: ros interface sstp
  hosts: all
  gather_facts: no
  connection: local

  roles:
  - role: nikolaydachev.routeros_api.ros_int_sstp
    ros_int_sstp_config:
      - server_user_int
      - server
      - client