- name: ros interface bridge example
  hosts: all
  gather_facts: no
  connection: local

  tasks:
    - name: Bridge Config
      include_role: 
        name: nikolaydachev.routeros_api.ros_int_bridge
      vars:
        ros_int_bridge_config: "{{ item.ros_int_bridge_config }}"

        ros_int_bridge_name: "{{ item.ros_int_bridge_name }}"

        ros_int_bridge_port_bridge: "{{ item.ros_int_bridge_port_bridge }}"
        ros_int_bridge_port_interface: "{{ item.ros_int_bridge_port_interface }}"

        ros_int_bridge_vlan_bridge: "{{ item.ros_int_bridge_vlan_bridge }}"
        ros_int_bridge_vlan_untagged: "{{ item.ros_int_bridge_vlan_untagged }}"
        ros_int_bridge_vlan_vlan_ids: "{{ item.ros_int_bridge_vlan_vlan_ids }}"

        ros_int_bridge_acl_flush: "{{ item.ros_int_bridge_acl_flush }}"
        ros_int_bridge_filter: "{{ item.ros_int_bridge_filter }}"

      loop:
        "{{ ros_int_bridge }}"