- name: ros vrrp with dhcp server
  hosts: all
  gather_facts: no
  connection: local

  roles:
  # add ip address to interface from vrrp vip network
  - role: nikolaydachev.routeros_api.ros_ip_addr
    ip_addr_interface: "{{ ros_int_vrrp_interface }}"
    ip_addr_address: "{{ ros_int_vrrp_lan_ip }}"

  # configure vrrp
  - role: nikolaydachev.routeros_api.ros_int_vrrp

  # add vrrp vip address
  - role: nikolaydachev.routeros_api.ros_ip_addr
    ip_addr_interface: "{{ ros_int_vrrp_name }}"
    ip_addr_address: "{{ ros_int_vrrp_vip }}"

  # create ip pool from vrrp vip network
  - role: nikolaydachev.routeros_api.ros_ip_pool

  # configure dhcp server for vrrp vip / network
  - role: nikolaydachev.routeros_api.ros_ip_dhcp_server
    dhcp_server_config:
      - network
      - server
