- name: ros ip dhcp-server 
  hosts: all
  gather_facts: no
  connection: local

  roles:
#  - role: nikolaydachev.routeros_api.ros_ip_pool
  - role: nikolaydachev.routeros_api.ros_ip_dhcp_server
    ros_ip_dhcp_server_config:
      - network
      - server
#      - lease
#      - options
#      - vci
