- name: ros ip firewall
  hosts: all
  gather_facts: no
  connection: local

  roles:
  - role: nikolaydachev.routeros_api.ros_ip_firewall
    ros_ip_firewall_config:
      - address-list
      - service-port
      - nat
      - raw
      - filter
      - calea
      - layer7-protocol
      - mangle
      - connection-tracking
