- name: ros interface vrrp 
  hosts: all
  gather_facts: no
  connection: local

  roles:
  - role: nikolaydachev.routeros_api.ros_int_vrrp
  - role: nikolaydachev.routeros_api.ros_ip_addr
    ip_addr_interface: "{{ ros_int_vrrp_name }}"
    ip_addr_address: "{{ ros_int_vrrp_vip }}"
