- name: ros remove example
  hosts: all
  gather_facts: no
  connection: local

  roles:
  - role: nikolaydachev.routeros_api.ros_remove
    ros_remove_path: "ip firewall filter"
    #ros_remove_id: "*99"