---
- name: configure user
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    ssl: "{{ ros_ssl }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_user_path }}"
    add:

  register: user
  delegate_to: localhost

- name: result configure user
  debug:
    msg: "{{ user }}"

