---
- name: configure user ssh-keys private
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    ssl: "{{ ros_ssl }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_user_ssh_keys_private_path }}"
    cmd:
      import
      "{{ ros_user_ssh_keys_private_user }}"
      "{{ ros_user_ssh_keys_private_passphrase }}"
      "{{ ros_user_ssh_keys_private_private_key_file }}"
      "{{ ros_user_ssh_keys_private_public_key_fil }}"
  register: usersshkeysprivate
  delegate_to: localhost

- name: result configure user ssh-keys private
  debug:
    msg: "{{ usersshkeysprivate }}"

