---
- name: configure user group
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    ssl: "{{ ros_ssl }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_user_group_path }}"
    add:
      comment={{ ros_user_group_comment }}
      copy-from={{ ros_user_group_copy_from }}
      name={{ ros_user_group_name }}
      policy={{ ros_user_group_policy }}
      skin={{ ros_user_group_skin }}
  register: usergroup
  delegate_to: localhost

- name: result configure user group
  debug:
    msg: "{{ usergroup }}"
