---
# tasks file for ros_ip_dns
- name: configure dns server
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    ssl: "{{ ros_ssl }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_ip_dns_path }}"
    cmd:
      set
      allow-remote-requests="{{ ros_ip_dns_allow_remote_requests }}"
      max-concurrent-queries="{{ ros_ip_dns_max_concurrent_queries }}"
      query-server-timeout="{{ ros_ip_dns_query_server_timeout }}"
      use-doh-server="{{ ros_ip_dns_use_doh_server }}"
      cache-max-ttl="{{ ros_ip_dns_cache_max_ttl }}"
      max-concurrent-tcp-sessions="{{ ros_ip_dns_max_concurrent_tcp_sessions }}"
      query-total-timeout="{{ ros_ip_dns_query_total_timeout }}"
      verify-doh-cert="{{ ros_ip_dns_verify_doh_cert }}"
      cache-size="{{ ros_ip_dns_cache_size }}"
      max-udp-packet-size="{{ ros_ip_dns_max_udp_packet_size }}"
      servers="{{ ros_ip_dns_servers }}"
  register: dnsserverout
  delegate_to: localhost

- name: result configure dns server
  debug:
    msg: "{{ dnsserverout }}"