---
- name: RESET CONFIGURATION!
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    ssl: "{{ ros_ssl }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_reset_config_path }}"
    cmd:
      reset-configuration
      caps-mode="{{ ros_reset_config_caps_mode }}"
      keep-users="{{ ros_reset_config_keep_users }}"
      no-defaults="{{ ros_reset_config_no_defaults }}"
      run-after-reset="{{ ros_reset_config_run_after_reset }}"
      skip-back="{{ ros_reset_config_skip_back }}"

  register: resetout
  delegate_to: localhost

- name: result for reset-configuration
  debug:
    msg: "{{ resetout }}"
