---
# defaults file for ros_routing_ospf
  ros_hostname: "{{ inventory_hostname }}"
  ros_username: "admin"
  ros_password: ""
  ros_ssl: "true"

  ros_routing_ospf_path: "routing ospf"
  ros_routing_ospf_config: []

  ros_routing_ospf_area_path: "{{ ros_routing_ospf_path }} area"
  ros_routing_ospf_area_area_id: ""
  ros_routing_ospf_area_copy_from: ""
  ros_routing_ospf_area_disabled: "no"
  ros_routing_ospf_area_instance: ""
  ros_routing_ospf_area_translator_role: ""
  ros_routing_ospf_area_comment: ""
  ros_routing_ospf_area_default_cost: ""
  ros_routing_ospf_area_inject_summary_lsas: ""
  ros_routing_ospf_area_name: ""
  ros_routing_ospf_area_type: ""

  ros_routing_ospf_area_range_path:  "{{ ros_routing_ospf_path }} area range"
  ros_routing_ospf_area_range_advertise: ""
  ros_routing_ospf_area_range_comment: ""
  ros_routing_ospf_area_range_copy_from: ""
  ros_routing_ospf_area_range_cost: ""
  ros_routing_ospf_area_range_disabled: "no"
  ros_routing_ospf_area_range_range: ""
  ros_routing_ospf_area_range_area: ""

  ros_routing_ospf_instance_path: "{{ ros_routing_ospf_path }} instance"
  ros_routing_ospf_instance_comment: ""
  ros_routing_ospf_instance_disabled: "no"
  ros_routing_ospf_instance_domain_id: ""
  ros_routing_ospf_instance_in_filter: ""
  ros_routing_ospf_instance_metric_connected: ""
  ros_routing_ospf_instance_metric_other_ospf: ""
  ros_routing_ospf_instance_metric_static: ""
  ros_routing_ospf_instance_mpls_te_router_id: ""
  ros_routing_ospf_instance_out_filter: ""
  ros_routing_ospf_instance_router_id: ""
  ros_routing_ospf_instance_use_dn: ""
  ros_routing_ospf_instance_copy_from: ""
  ros_routing_ospf_instance_distribute_default: ""
  ros_routing_ospf_instance_domain_tag: ""
  ros_routing_ospf_instance_metric_bgp: ""
  ros_routing_ospf_instance_metric_default: ""
  ros_routing_ospf_instance_metric_rip: ""
  ros_routing_ospf_instance_mpls_te_area: ""
  ros_routing_ospf_instance_name: ""
  ros_routing_ospf_instance_routing_table: ""
  ros_routing_ospf_instance_redistribute_bgp: ""
  ros_routing_ospf_instance_redistribute_connected: ""
  ros_routing_ospf_instance_redistribute_other_ospf: ""
  ros_routing_ospf_instance_redistribute_rip: ""
  ros_routing_ospf_instance_redistribute_static: ""

  ros_routing_ospf_nbma_neighbor_path: "{{ ros_routing_ospf_path }} nbma-neighbor"
  ros_routing_ospf_nbma_neighbor_address: ""
  ros_routing_ospf_nbma_neighbor_comment: ""
  ros_routing_ospf_nbma_neighbor_copy_from: ""
  ros_routing_ospf_nbma_neighbor_disabled: "no"
  ros_routing_ospf_nbma_neighbor_instance: ""
  ros_routing_ospf_nbma_neighbor_poll_interval: ""
  ros_routing_ospf_nbma_neighbor_priority: ""

  ros_routing_ospf_interface_path: "{{ ros_routing_ospf_path }} interface"
  ros_routing_ospf_interface_authentication: ""
  ros_routing_ospf_interface_authentication_key_id: ""
  ros_routing_ospf_interface_copy_from: ""
  ros_routing_ospf_interface_dead_interval: ""
  ros_routing_ospf_interface_hello_interval: ""
  ros_routing_ospf_interface_interface: ""
  ros_routing_ospf_interface_passive: ""
  ros_routing_ospf_interface_retransmit_interval: ""
  ros_routing_ospf_interface_use_bfd: ""
  ros_routing_ospf_interface_authentication_key: ""
  ros_routing_ospf_interface_comment: ""
  ros_routing_ospf_interface_cost: ""
  ros_routing_ospf_interface_disabled: "no"
  ros_routing_ospf_interface_instance_id: ""
  ros_routing_ospf_interface_network_type: ""
  ros_routing_ospf_interface_priority: ""
  ros_routing_ospf_interface_transmit_delay: ""

  ros_routing_ospf_sham_link_path: "{{ ros_routing_ospf_path }} sham-link"
  ros_routing_ospf_sham_link_comment: ""
  ros_routing_ospf_sham_link_copy_from: ""
  ros_routing_ospf_sham_link_cost: ""
  ros_routing_ospf_sham_link_disabled: "no"
  ros_routing_ospf_sham_link_area: ""
  ros_routing_ospf_sham_link_dst_address: ""
  ros_routing_ospf_sham_link_src_address: ""

  ros_routing_ospf_network_path: "{{ ros_routing_ospf_path }} network"
  ros_routing_ospf_network_comment: ""
  ros_routing_ospf_network_copy_from: ""
  ros_routing_ospf_network_disabled: "no"
  ros_routing_ospf_network_network: ""
  ros_routing_ospf_network_area: ""

  ros_routing_ospf_virtual_link_path: "{{ ros_routing_ospf_path }} virtual-link"
  ros_routing_ospf_virtual_link_authentication: ""
  ros_routing_ospf_virtual_link_authentication_key: ""
  ros_routing_ospf_virtual_link_authentication_key_id: ""
  ros_routing_ospf_virtual_link_comment: ""
  ros_routing_ospf_virtual_link_copy_from: ""
  ros_routing_ospf_virtual_link_disabled: "no"
  ros_routing_ospf_virtual_link_instance_id: ""
  ros_routing_ospf_virtual_link_use_bfd: ""
  ros_routing_ospf_virtual_link_neighbor_id: ""
  ros_routing_ospf_virtual_link_transit_area: ""
