---
# tasks file for ros_api_demo
- name: add - "ip address add {{ ros_t_addips[0] }}" "ip address add {{ ros_t_addips[1] }}"
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_t_path }}"
    ssl: "{{ ros_ssl }}"
    add: "{{ item }}"
  loop: "{{ ros_t_addips }}"
  register: addout
  delegate_to: localhost

- name: result - routeros '.id' for new added items
  debug:
    msg: '{{ addout }}'
