---
# tasks file for ros_api_demo
- name: get - "{{ ros_t_path }} print"
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    ssl: "{{ ros_ssl }}"
    path: "{{ ros_t_path }}"
  register: print_path
  delegate_to: localhost

- name: result - "{{ ros_t_path }} print"
  debug:
    msg: '{{ print_path }}'
