---
- name: query for items to flush {{ ros_flush_type }}
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    ssl: "{{ ros_ssl }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_flush_path }}"
    query: ".id"
  register: rosflushfind
  delegate_to: localhost

- name: create a list of query result for {{ ros_flush_type }} to flush
  vars:
    to_be_flush: ""
  ansible.builtin.set_fact:
    to_be_flush: "{{ to_be_flush + ',' + item['.id'] }}"
  loop: "{{ rosflushfind.msg }}"
  when: '"no results for" not in rosflushfind.msg.0'

- name: flush {{ ros_flush_type }} items
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    ssl: "{{ ros_ssl }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_flush_path }}"
    remove: "{{ to_be_flush }}"
  register: rosflush
  delegate_to: localhost
  when: '"no results for" not in rosflushfind.msg.0'
