---
- name: Clear vars
  ansible.builtin.set_fact:
    rosflushfind: ""
    to_be_flush: ""
    flush_id_item: ""

- name: query '{{ ros_flush_query }}' for items to flush
  vars:
    rosflushfind: ""
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    ssl: "{{ ros_ssl }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_flush_path }}"
    query: "{{ ros_flush_query }}"
  register: rosflushfind
  delegate_to: localhost

- name: create a list of query result for {{ ros_flush_path }} to flush
  vars:
    to_be_flush: ""
    flush_id_item: ""
  ansible.builtin.set_fact:
    to_be_flush: "{{ to_be_flush + ',' + flush_id_item['.id'] }}"
  loop: "{{ rosflushfind.msg }}"
  loop_control:
    loop_var: flush_id_item
  when: '"no results for" not in rosflushfind.msg.0'

- name: flush {{ ros_flush_path }} items
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    ssl: "{{ ros_ssl }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_flush_path }}"
    remove: "{{ to_be_flush[1:] }}"
  register: rosflush
  delegate_to: localhost
  when: to_be_flush
