---
# defaults file for ros_ppp
ros_hostname: "{{ inventory_hostname }}"
ros_username: "admin"
ros_password: ""
ros_ssl: "true"

ros_ppp_path: "ppp"
ros_ppp_config: []

# set
ros_ppp_aaa_path: "{{ ros_ppp_path }} aaa"
ros_ppp_aaa_accounting: ""
ros_ppp_aaa_interim_update: ""
ros_ppp_aaa_use_circuit_id_in_nas_port_id: ""
ros_ppp_aaa_use_radius: ""

ros_ppp_l2tp_secret_path: "{{ ros_ppp_path }} l2tp-secret"
ros_ppp_l2tp_secret_address: ""
ros_ppp_l2tp_secret_comment: ""
ros_ppp_l2tp_secret_copy_from: ""
ros_ppp_l2tp_secret_secret: ""

ros_ppp_profile_path: "{{ ros_ppp_path }} profile"
ros_ppp_profile_address_list: ""
ros_ppp_profile_bridge_learning: ""
ros_ppp_profile_change_tcp_mss: ""
ros_ppp_profile_dhcpv6_pd_pool: ""
ros_ppp_profile_incoming_filter: ""
ros_ppp_profile_local_address: ""
ros_ppp_profile_only_one: ""
ros_ppp_profile_queue_type: ""
ros_ppp_profile_remote_ipv6_prefix_pool: ""
ros_ppp_profile_use_encryption: ""
ros_ppp_profile_use_upnp: ""
ros_ppp_profile_bridge: ""
ros_ppp_profile_bridge_path_cost: ""
ros_ppp_profile_comment: ""
ros_ppp_profile_dns_server: ""
ros_ppp_profile_insert_queue_before: ""
ros_ppp_profile_on_down: ""
ros_ppp_profile_outgoing_filter: ""
ros_ppp_profile_rate_limit: ""
ros_ppp_profile_session_timeout: ""
ros_ppp_profile_use_ipv6: ""
ros_ppp_profile_wins_server: ""
ros_ppp_profile_bridge_horizon: ""
ros_ppp_profile_bridge_port_priority: ""
ros_ppp_profile_copy_from: ""
ros_ppp_profile_idle_timeout: ""
ros_ppp_profile_interface_list: ""
ros_ppp_profile_on_up: ""
ros_ppp_profile_parent_queue: ""
ros_ppp_profile_remote_address: ""
ros_ppp_profile_use_compression: ""
ros_ppp_profile_use_mpls: ""
ros_ppp_profile_name: ""

ros_ppp_secret_path: "{{ ros_ppp_path }} secret"
ros_ppp_secret_caller_id: ""
ros_ppp_secret_comment: ""
ros_ppp_secret_copy_from: ""
ros_ppp_secret_disabled: "no"
ros_ppp_secret_ipv6_routes: ""
ros_ppp_secret_limit_bytes_in: ""
ros_ppp_secret_limit_bytes_out: ""
ros_ppp_secret_local_address: ""
ros_ppp_secret_password: ""
ros_ppp_secret_profile: ""
ros_ppp_secret_remote_address: ""
ros_ppp_secret_remote_ipv6_prefix: ""
ros_ppp_secret_routes: ""
ros_ppp_secret_service: ""
ros_ppp_secret_name: ""
