---
# defaults file for ros_int_eoip
ros_hostname: "{{ inventory_hostname }}"
ros_username: "admin"
ros_password: ""
ros_ssl: "true"

ros_int_eoip_path: "interface eoip"

ros_int_eoip_allow_fast_path: ""
ros_int_eoip_arp_timeout: ""
ros_int_eoip_comment: ""
ros_int_eoip_disabled: "no"
ros_int_eoip_dscp: ""
ros_int_eoip_keepalive: ""
ros_int_eoip_loop_protect: ""
ros_int_eoip_loop_protect_send_interval: ""
ros_int_eoip_mtu: ""
ros_int_eoip_remote_address: ""
ros_int_eoip_arp: ""
ros_int_eoip_clamp_tcp_mss: ""
ros_int_eoip_copy_from: ""
ros_int_eoip_dont_fragment: ""
ros_int_eoip_ipsec_secret: ""
ros_int_eoip_local_address: ""
ros_int_eoip_loop_protect_disable_time: ""
ros_int_eoip_mac_address: ""
ros_int_eoip_name: ""
ros_int_eoip_tunnel_id: ""
