---
# tasks file for ros_int_ovpn
- name: configure ovpn client interface
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    ssl: "{{ ros_ssl }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_int_ovpn_client_path }}"
    add:
      add-default-route="{{ ros_int_ovpn_client_add_default_route }}"
      auth="{{ ros_int_ovpn_client_auth }}"
      certificate="{{ ros_int_ovpn_client_certificate }}"
      cipher="{{ ros_int_ovpn_client_cipher }}"
      comment="{{ ros_int_ovpn_client_comment }}"
      copy-from="{{ ros_int_ovpn_client_copy_from }}"
      disabled="{{ ros_int_ovpn_client_disabled }}"
      mac-address="{{ ros_int_ovpn_client_mac_address }}"
      max-mtu="{{ ros_int_ovpn_client_max_mtu }}"
      mode="{{ ros_int_ovpn_client_mode }}"
      name="{{ ros_int_ovpn_client_name }}"
      password="{{ ros_int_ovpn_client_password }}"
      port="{{ ros_int_ovpn_client_port }}"
      profile="{{ ros_int_ovpn_client_profile }}"
      use-peer-dns="{{ ros_int_ovpn_client_use_peer_dns }}"
      verify-server-certificate="{{ ros_int_ovpn_client_verify_server_certificate }}"
      connect-to="{{ ros_int_ovpn_client_connect_to }}"
      user="{{ ros_int_ovpn_client_user }}"
  register: intovpnclientout
  delegate_to: localhost

- name: result ovpn client interface config
  debug:
    msg: '{{ intovpnclientout }}'