---
# tasks file for ros_int_ovpn
  - import_tasks: server_user_int.yml
    when: '"server_user_int" in ros_int_ovpn_config'

  - import_tasks: server.yml
    when: '"server" in ros_int_ovpn_config'

  - import_tasks: client.yml
    when: '"client" in ros_int_ovpn_config'