# tasks file for ros_caps_man
---
- name: add caps-man aaa
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    ssl: "{{ ros_ssl }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_caps_man_aaa_path }}"
    add:

  register: roscapsmanaaa
  delegate_to: localhost