# tasks file for ros_caps_man
---
- name: caps-man aaa set
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    ssl: "{{ ros_ssl }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_caps_man_aaa_path }}"
    cmd:
      set
      called-format="{{ ros_caps_man_aaa_called_format }}"
      interim-update="{{ ros_caps_man_aaa_interim_update }}"
      mac-caching="{{ ros_caps_man_aaa_mac_caching }}"
      mac-format="{{ ros_caps_man_aaa_mac_format }}"
      mac-mode="{{ ros_caps_man_aaa_mac_mode }}"
  register: roscapsmanaaa
  delegate_to: localhost