# tasks file for ros_caps_man
---
- name: add caps-man access-list
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    ssl: "{{ ros_ssl }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_caps_man_access_list_path }}"
    add:
      action="{{ ros_caps_man_access_action }}"
      ap-tx-limit="{{ ros_caps_man_access_ap_tx_limit }}"
      client-tx-limit="{{ ros_caps_man_access_client_tx_limit }}"
      copy-from="{{ ros_caps_man_access_copy_from }}"
      interface="{{ ros_caps_man_access_interface }}"
      mac-address-mask="{{ ros_caps_man_access_mac_address_mask }}"
      private-passphrase="{{ ros_caps_man_access_private_passphrase }}"
      signal-range="{{ ros_caps_man_access_signal_range }}"
      time="{{ ros_caps_man_access_time }}"
      vlan-mode="{{ ros_caps_man_access_vlan_mode }}"
      allow-signal-out-of-range="{{ ros_caps_man_access_allow_signal_out_of_range }}"
      client-to-client-forwarding="{{ ros_caps_man_access_client_to_client_forwarding }}"
      comment="{{ ros_caps_man_access_comment }}"
      disabled="{{ ros_caps_man_access_disabled }}"
      mac-address="{{ ros_caps_man_access_mac_address }}"
      place-before="{{ ros_caps_man_access_place_before }}"
      radius-accounting="{{ ros_caps_man_access_radius_accounting }}"
      ssid-regexp="{{ ros_caps_man_access_ssid_regexp }}"
      vlan-id="{{ ros_caps_man_access_vlan_id }}"
  register: roscapsmanaccesslist
  delegate_to: localhost