# tasks file for ros_caps_man
---
- name: set caps-man actual-interface-configuration
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    ssl: "{{ ros_ssl }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_caps_man_actual_interface_configuration_path }}"
    cmd:
      set
      arp="{{ ros_caps_man_actual_interface_configuration_arp }}"
      comment="{{ ros_caps_man_actual_interface_configuration_comment }}"
      disable-running-check="{{ ros_caps_man_actual_interface_configuration_disable_running_check }}"
      mac-address="{{ ros_caps_man_actual_interface_configuration_mac_address }}"
      name="{{ ros_caps_man_actual_interface_configuration_name }}"
      arp-timeout="{{ ros_caps_man_actual_interface_configuration_arp_timeout }}"
      disabled="{{ ros_caps_man_actual_interface_configuration_disabled }}"
      master-interface="{{ ros_caps_man_actual_interface_configuration_master_interface }}"
      numbers="{{ ros_caps_man_actual_interface_configuration_numbers }}"
      l2mtu="{{ ros_caps_man_actual_interface_configuration_l2mtu }}"
      mtu="{{ ros_caps_man_actual_interface_configuration_mtu }}"
      radio-mac="{{ ros_caps_man_actual_interface_configuration_radio_mac }}"
   
  register: roscapsmanactualinterfaceconfiguration
  delegate_to: localhost