---
- name: set ip service {{ item.key }}
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    ssl: "{{ ros_ssl }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_ip_service_path }}"
    cmd: "set numbers={{ item.key }} {{ item.value | join(' ') }}"
  register: ipsrvsetout
  delegate_to: localhost
  loop: "{{ lookup('dict', ros_ip_service_set) }}"

- name: result ip service set
  debug:
    msg: '{{ ipsrvsetout }}'
