---
# tasks file for ros_ppp
- name: configure ppp l2tp-secret
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    ssl: "{{ ros_ssl }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_ppp_l2tp_secret_path }}"
    add:
      address="{{ ros_ppp_l2tp_secret_address }}"
      comment="{{ ros_ppp_l2tp_secret_comment }}"
      copy-from="{{ ros_ppp_l2tp_secret_copy_from }}"
      secret="{{ ros_ppp_l2tp_secret_secret }}"
  register: pppl2tpsecretout
  delegate_to: localhost

- name: result ppp config
  debug:
    msg: '{{ pppl2tpsecretout }}'
