---
# tasks file for ros_ppp
- name: configure ppp
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    ssl: "{{ ros_ssl }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_ppp_secret_path }}"
    add:
      caller-id="{{ ros_ppp_secret_caller_id }}"
      comment="{{ ros_ppp_secret_comment }}"
      copy-from="{{ ros_ppp_secret_copy_from }}"
      disabled="{{ ros_ppp_secret_disabled }}"
      ipv6-routes="{{ ros_ppp_secret_ipv6_routes }}"
      limit-bytes-in="{{ ros_ppp_secret_limit_bytes_in }}"
      limit-bytes-out="{{ ros_ppp_secret_limit_bytes_out }}"
      local-address="{{ ros_ppp_secret_local_address }}"
      password="{{ ros_ppp_secret_password }}"
      profile="{{ ros_ppp_secret_profile }}"
      remote-address="{{ ros_ppp_secret_remote_address }}"
      remote-ipv6-prefix="{{ ros_ppp_secret_remote_ipv6_prefix }}"
      routes="{{ ros_ppp_secret_routes }}"
      service="{{ ros_ppp_secret_service }}"
      name="{{ ros_ppp_secret_name }}"
  register: pppsecretout
  delegate_to: localhost

- name: result ppp secret config
  debug:
    msg: '{{ pppsecretout }}'
