---
# defaults file for ros_int_ovpn
ros_hostname: "{{ inventory_hostname }}"
ros_username: "admin"
ros_password: ""
ros_ssl: "true"

ros_int_ovpn_server_path: "interface ovpn-server"
ros_int_ovpn_client_path: "interface ovpn-client"
ros_int_ovpn_config: []

ros_int_ovpn_server_interface_comment: ""
ros_int_ovpn_server_interface_copy_from: ""
ros_int_ovpn_server_interface_disabled: "no"
ros_int_ovpn_server_interface_name: ""
ros_int_ovpn_server_interface_user: ""

ros_int_ovpn_server_server_path: "{{ ros_int_ovpn_server_path }} server"
ros_int_ovpn_server_server_auth: ""
ros_int_ovpn_server_server_certificate: ""
ros_int_ovpn_server_server_cipher: ""
ros_int_ovpn_server_server_default_profile: ""
ros_int_ovpn_server_server_enabled: ""
ros_int_ovpn_server_server_keepalive_timeout: ""
ros_int_ovpn_server_server_mac_address: ""
ros_int_ovpn_server_server_max_mtu: ""
ros_int_ovpn_server_server_mode: ""
ros_int_ovpn_server_server_netmask: ""
ros_int_ovpn_server_server_port: ""
ros_int_ovpn_server_server_require_client_certificate: ""

ros_int_ovpn_client_add_default_route: ""
ros_int_ovpn_client_auth: ""
ros_int_ovpn_client_certificate: ""
ros_int_ovpn_client_cipher: ""
ros_int_ovpn_client_comment: ""
ros_int_ovpn_client_copy_from: ""
ros_int_ovpn_client_disabled: "no"
ros_int_ovpn_client_mac_address: ""
ros_int_ovpn_client_max_mtu: ""
ros_int_ovpn_client_mode: ""
ros_int_ovpn_client_name: ""
ros_int_ovpn_client_password: ""
ros_int_ovpn_client_port: ""
ros_int_ovpn_client_profile: ""
ros_int_ovpn_client_use_peer_dns: ""
ros_int_ovpn_client_verify_server_certificate: ""
ros_int_ovpn_client_connect_to: ""
ros_int_ovpn_client_user: ""