---
# tasks file for routeros_api
- name: get - "{{ ros_t_path }} print"
  routeros_api:
    hostname: "{{ ros_hostname }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
  register: conn
  delegate_to: localhost

- name: result - "{{ ros_t_path }} print"
  debug:
    msg: '{{ conn }}'
