
namespace: nikolaydachev
name: routeros_api
version: 1.3.0
readme: README.md

authors:
- Nikolay Dachev <nikolay@dachev.info>

description: RouterOS configuration via ansible module community.routeros.api

license:
- GPL-3.0-or-later

tags: ['routeros', 'mikrotik', 'api']

