---
- name: configure system identity
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    ssl: "{{ ros_ssl }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_user_path }}"
    cmd:
      set
      name="{{ ros_sys_identity_name }}"

  register: systemidentity
  delegate_to: localhost

- name: result configure system identity
  debug:
    msg: "{{ systemidentity }}"
