---
- name: flush {{ ros_int_bridge_acl_path }}
  import_role:
    name: nikolaydachev.routeros_api.ros_flush
  vars:
    ros_flush_path: "{{ ros_int_bridge_acl_path }}"
  when: ros_int_bridge_acl_flush == "true"

- name: add {{ ros_int_bridge_acl_path }}
  import_role:
    name: nikolaydachev.routeros_api.ros_add
  vars:
    ros_add_path: "{{ ros_int_bridge_acl_path }}"
    ros_add_list: "{{ ros_int_bridge_acl_rules }}"