---
# tasks file for ros_int_bridge
  - import_tasks: add.yml
    when: '"add" in ros_int_bridge_config'

  - import_tasks: host.yml
    when: '"host" in ros_int_bridge_config'

  - import_tasks: mdb.yml
    when: '"mdb" in ros_int_bridge_config'

  - import_tasks: msti.yml
    when: '"msti" in ros_int_bridge_config'

  - import_tasks: port-controller.yml
    when: '"port-controller" in ros_int_bridge_config'

  - import_tasks: port-controller.yml
    when: '"port-controller_device" in ros_int_bridge_config'

  - import_tasks: port-controller.yml
    when: '"port-controller_path" in ros_int_bridge_config'

  - import_tasks: port-extender.yml
    when: '"port-extender" in ros_int_bridge_config'

  - import_tasks: port.yml
    when: '"port" in ros_int_bridge_config'

  - import_tasks: settings.yml
    when: '"settings" in ros_int_bridge_config'

  - import_tasks: vlan.yml
    when: '"vlan" in ros_int_bridge_config'

  - name: "interface bridge calea"
    import_tasks: acl.yml
    vars:
      ros_int_bridge_acl_path: "{{ ros_int_bridge_calea_path }}"
      ros_int_bridge_acl_rules: "{{ ros_int_bridge_calea }}"
    when: '"calea" in ros_int_bridge_config'
  
  - name: "interface bridge filter"
    import_tasks: acl.yml
    vars:
      ros_int_bridge_acl_path: "{{ ros_int_bridge_filter_path }}"
      ros_int_bridge_acl_rules: "{{ ros_int_bridge_filter }}"
    when: '"filter" in ros_int_bridge_config'
  
  - name: "interface bridge nat"
    import_tasks: acl.yml
    vars:
      ros_int_bridge_acl_path: "{{ ros_int_bridge_nat_path }}"
      ros_int_bridge_acl_rules: "{{ ros_int_bridge_nat }}"
    when: '"nat" in ros_int_bridge_config'