---
- name: add interface bridge msti
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    ssl: "{{ ros_ssl }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_int_bridge_msti_path }}"
    add:
      bridge="{{ ros_int_bridge_msti_bridge }}"
      comment="{{ ros_int_bridge_msti_comment }}"
      copy-from="{{ ros_int_bridge_msti_copy_from }}"
      msti-copy-from="{{ ros_int_bridge_msti_disabled }}"
      identifier="{{ ros_int_bridge_msti_identifier }}"
      priority="{{ ros_int_bridge_msti_priority }}"
      vlan-mapping="{{ ros_int_bridge_msti_vlan_mapping }}"
  register: rosintbridgemsti
  delegate_to: localhost