---
- name: add interface bridge port
  community.routeros.api:
    hostname: "{{ ros_hostname }}"
    ssl: "{{ ros_ssl }}"
    password: "{{ ros_password }}"
    username: "{{ ros_username }}"
    path: "{{ ros_int_bridge_vlan_path }}"
    add:
      bridge="{{ ros_int_bridge_vlan_bridge }}"
      comment="{{ ros_int_bridge_vlan_comment }}"
      copy-from="{{ ros_int_bridge_vlan_copy_from }}"
      disabled="{{ ros_int_bridge_vlan_disabled }}"
      tagged="{{ ros_int_bridge_vlan_tagged }}"
      untagged="{{ ros_int_bridge_vlan_untagged }}"
      vlan-ids="{{ ros_int_bridge_vlan_vlan_ids }}"
  register: rosintbridgevlan
  delegate_to: localhost